name: CoinsLab
description: Just watch.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.8
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  carousel_slider: ^4.2.1
  nanoid: ^1.0.0
  intl: ^0.19.0
  fl_chart: ^0.65.0
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.3.0
  top_snackbar_flutter: ^3.1.0
  provider: ^6.1.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - images/test.jpg
    - images/1.gif
    - images/2.gif
    - images/3.gif
    - images/4.gif
    - images/5.gif
    - images/asset1.jpg
    - images/asset2.jpg
    - images/asset3.jpg
  fonts:
      - family: Inter
        fonts:
          - asset: fonts/inter-Light.ttf
          - asset: fonts/inter-ExtraLight.ttf
            style: normal
      - family: Inter
        fonts:
          - asset: fonts/inter-Regular.ttf
          - asset: fonts/inter-SemiBold.ttf
            weight: 700